// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLPBmkGA5qVz95qjsc5IySf0x8Ez45BA',
    appId: '1:512772846655:web:3fb1d42b15c08254bb748a',
    messagingSenderId: '512772846655',
    projectId: 'flutterproject-cd89b',
    authDomain: 'flutterproject-cd89b.firebaseapp.com',
    databaseURL: 'https://flutterproject-cd89b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterproject-cd89b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALFfJGPVFFMHqDdjoAQNWfmTpaULOPozE',
    appId: '1:512772846655:android:223b5f05cbbcafa9bb748a',
    messagingSenderId: '512772846655',
    projectId: 'flutterproject-cd89b',
    databaseURL: 'https://flutterproject-cd89b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterproject-cd89b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBE0N_HFt6yEaj6nrNPKQCRQVksyki_s',
    appId: '1:512772846655:ios:8aa3725aa4b22c65bb748a',
    messagingSenderId: '512772846655',
    projectId: 'flutterproject-cd89b',
    databaseURL: 'https://flutterproject-cd89b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterproject-cd89b.appspot.com',
    iosBundleId: 'com.example.learnflutternew',
  );
}
